# Generated by Django 3.0.4 on 2020-07-13 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200701_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
