# Generated by Django 3.0.4 on 2020-07-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_modified_string',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
